### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by eigenein** [eigenein/protobuf#6]

**Comment by bbayles** [comment]
I did some more digging on this after PR #7 .

If we change the `'name'` and `'type'` encodings to `Unicode`, then very little has to change to make both Python 2 and 3 work with the same code.

There's probably not an objectively correct answer here - when we add a field, we can then use it as a Python attribute (e.g. `instance.added_field_name`). In Python that has to be an identifier, and that identifier can be referred to (e.g. by `getattr()`) by the `str` type. The problem is that `str` is different on Python 2 and 3.

Option 1 seems to be what I've done [here](https://github.com/eigenein/protobuf/blob/e1d8ca6bfb6a4ce807ca68164d9e50929aaf59ac/pure_protobuf/protobuf.py#L612-L617) - serialized `'name'` and `'type'` to `Unicode`.

Option 2 would be something like: "make it `Unicode` on Python 3 and `Bytes` on Python 2".

I could see an argument for either - what do you think?

**Comment by eigenein** [comment]
Sorry for the really slow response.

I would prefer the first option, it rather corresponds to the nature of these fields as they're texts. Also, as 2020 is approaching, we could eventually drop Python 2 support for the new fixes/features.
